#!/bin/sh
module="secvault"
device="secvault"
ctrldevice="sv_ctl"
major=231

/sbin/insmod ./$module.ko $* || exit 1

rm -f /dev/${ctrldevice}
mknod /dev/${ctrldevice} c $major 0

rm -f /dev/${device}[0-3]
mknod /dev/${device}0 c $major 1 
mknod /dev/${device}1 c $major 2 
mknod /dev/${device}2 c $major 3
mknod /dev/${device}3 c $major 4

